apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default-namespace
spec:
  selector:
    app: tech-challenge-order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: LoadBalancer